lang: "en"

provider:
  driver: "mongodb"
  host: "localhost"
  port: 27017
  database: "minecraft"
  user: ""
  pass: ""

  # For SQL Databases
  prefix: "nickname_"
  table: "users"

  # For NoSQL Databases
  collection: "users"