name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
depends: ["Milkshake-Bukkit"]
commands:
  nick:
    description: "Change your nickname with this command"
  clearnick:
    description: "Clears your current nickname"
  realname:
    description: "See the realname of a player"
