name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  nick:
    description: "Change your nickname with this command."
  nicknames:
    description: "Base command of the Nicknames plugin"